### ISSUE TITLE
Horse Jump Height, HP Calculations Needs Adjustment

### ISSUE THREAD

**Issue by kc-** [TheAcademician/CobraCorral#4]
The statistics displayed by /horse-info seem to be off. Testing in-game suggests that the values displayed by the zyinhud mod are more accurate.
(Compare https://github.com/TheAcademician/CobraCorral/blob/master/src/us/drome/cobracorral/CorralListener.java#L150 and 
https://github.com/Zyin055/zyinhud/blob/master/src/main/java/com/zyin/zyinhud/mods/AnimalInfo.java#L515 for the jump height calculations)

**Comment by TheAcademician** [comment]
I have patched in the Zyin's formula for the jump height which indeed seems to be more accurate, thanks for suggesting it. The HP calculations seem to be OK from my testing, but I would welcome any examples of it being off.
